name: SNS Bot

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '30 */5 * * *'
    - cron: '*/10 * * * *' # 每 10 分鐘執行一次

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  SNS-Bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: run Python script
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      run:
        python main.py
  El7ZUP-Bot:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pip'
    - name: install python packages
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: run Python script
      env:
        ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        UPDATED_AT: ${{ vars.UPDATED_AT }}
      run:
        python el7zup_bot.py
